GET   http://localhost:3000/chromes
Content-Type: application/json

{   
    "playerName": "auri",
    "team": "los asdfgh",
    "country": "el pais de las maravillas",
    "position": "portera",
    "img": "shhhhhhhhhhhhhhhhhhhhh",
    "height": 160,
    "weight": 200,
    "appearanceRate": 100
}